services:
  marzban-node:
    image: gozargah/marzban-node:latest
    container_name: marzban-node
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      SSL_CLIENT_CERT_FILE: ${SSL_CLIENT_CERT_FILE}
      SERVICE_PORT: ${SERVICE_PORT}
      XRAY_API_PORT: ${XRAY_API_PORT}
      SERVICE_PROTOCOL: ${SERVICE_PROTOCOL:-rest}
    volumes:
      - ./data/marzban:/var/lib/marzban
      - ./data/marzban-node:/var/lib/marzban-node
